name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Copy deploy.sh
      run: cp deploy.sh $GITHUB_WORKSPACE/target/deploy.sh
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        run: cp $GITHUB_WORKSPACE/target/*.war /opt/payara41/glassfish/domains/domain1/autodeploy/
        script: |
          /opt/payara41/bin/asadmin deploy --contextroot /sg --force /opt/payara41/glassfish/domains/domain1/autodeploy/*.war

