name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Create deploy directory
        run: mkdir ${{ github.workspace }}/deploy

      - name: Copy WAR file
        run: cp ${{ github.workspace }}/target/*.war ${{ github.workspace }}/deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: war-file
          path: ${{ github.workspace }}/deploy/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: war-file
          path: ${{ github.workspace }}/deploy

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            FILE_PATH="${{ github.workspace }}/deploy/Teste-Deploy-1.0-SNAPSHOT.war"
            ls "$FILE_PATH"
            ls ${{ github.workspace }}/deploy/
            /opt/payara41/bin/asadmin deploy --contextroot /sg --force "$FILE_PATH"
